### ISSUE TITLE
Markus HW2 Automated Testing Unavailable On Student View + Potential Broken Tests

### ISSUE THREAD

**Issue by mistryrohan** [pointOfive/STA130_F23#7]
1. On the student view after submitting Homework 2, I am unable to see the automated testing option but on the Instructor View the file does seem to be there but I do not know how to make it visible on the student end

But I did have the previous solution file (with the asserts) downloaded before the new HW2 was committed and found 2 potential issues:

1.  On Test 5 it is 
assert Q5 == 0.692, "Try `(d[(d.Age>=25)&(d.Age<=40)].Survived=='Dead').mean()`"

The solution is 0.6925960637300843 so we should be asserting 0.693

2. On Test 6 it is
assert Q6 == (0.700, .032, 0.539), 'Try `(d.Survived[d.Paid>50]=="Dead").groupby(d.Man_Woman_or_Child).mean()`'

The value for children is 0.538462 so we should be asserting (0.700, .032, 0.538)

**Comment by lucieyang1** [comment]
For Q6, why would it be 0.538? I assumed "provide 3 decimal places rounding up" means to round the last place to the next highest one, no matter the following digits.

**Comment by mistryrohan** [comment]
Also a fair point I guess it's just how you interpret it. I was thinking it meant round up if like 1.234x if x >= 5

**Comment by pointOfive** [comment]
- Q5 -- good catch -- thanks: added `import numpy as np` and then used `assert Q5 == np.round(0.6925960637300843,3)`
- Q6: changed code `Q6 == (0.700, np.round(0.031746,3), np.round(0.538462,3))` but rounding was correct this time!

[commit/c489b71](https://github.com/pointOfive/STA130_F23/commit/c489b71cde6e82b59e77d969fe024224006b5fba)
