### ISSUE TITLE
HW2 Ambiguous Questions/MarkUs Tests

### ISSUE THREAD

**Issue by lucieyang1** [pointOfive/STA130_F23#8]
Hello!
Here's some issues I encountered with HW2:

- MarkUs tests fail if titanic.csv is not read into 'd'. Also for Q11, the code will give an error if the variable isn't called 'd' as well. We probably should specify that the name must be 'd', unless there's some other way around this.
- Rounding issues? The homework says to "provide 3 decimal places rounding up", so I would assume 0.243056 rounds up to 0.244 for Q4, but the correct answer is 0.243. It might be easier to ask for 3 decimal places rounded to have less confusion.
- For Q4 and Q6, the question asks for "proportion of deaths", but the variable names start with `prop_surv_`, which initially made me think we were still dealing with survival percentage. The variable names should probably be changed.
- Q7 asks to "interpret results for the previous questions", I think which questions exactly should be specified?

Overall, I think it was a pretty good homework! It took me around 1h30m, so I think the length is good.

**Comment by pointOfive** [comment]
- I had not added `titanic.csv` into the MarkUs autotesting environment, but have now! Thanks/Sorry!
- Changed the Q11 code to `pd.read_csv("titanic.csv").groupby('Man_Woman_or_Child').describe()` so `d` shouldn't be student facing any more
- Q4 and rounding -- I've not added hints and adjusted instructions for rounding with `numpy`
- Q4/Q6 variable names fixed!
- Q7 "compare and contrast Q6 versus Q6" specified

[commit/5e7131e84](https://github.com/pointOfive/STA130_F23/commit/5e7131e84d5ad91e9c2d4e05b7de9e780951e424)

**Comment by lucieyang1** [comment]
Ok, I tried naming the dataframe 'titanic' and the MarkUs tests still don't pass for Q4 and Q6, with the error "'DataFrame' object has no attribute 'Man_Woman_or_Child'", even though it works when I name the dataframe 'd'. I don't think it's an issue with my code? Thank you!
